all:
	mkdir -p ./downloaded_images/
	mkdir -p ./downloaded_images/train
	mkdir -p ./downloaded_images/test
	mkdir -p ./downloaded_images/train/melanoma
	mkdir -p ./downloaded_images/train/melanocytic_nevi
	mkdir -p ./downloaded_images/train/actinic_keratosis
	mkdir -p ./downloaded_images/train/BCC
	mkdir -p ./downloaded_images/train/benign_keratosis
	mkdir -p ./downloaded_images/train/vascular_lesion
	mkdir -p ./downloaded_images/train/dermatofibroma
	mkdir -p ./downloaded_images/test/melanoma
	mkdir -p ./downloaded_images/test/melanocytic_nevi
	mkdir -p ./downloaded_images/test/actinic_keratosis
	mkdir -p ./downloaded_images/test/BCC
	mkdir -p ./downloaded_images/test/benign_keratosis
	mkdir -p ./downloaded_images/test/vascular_lesion
	mkdir -p ./downloaded_images/test/dermatofibroma

	python3 ./download_images.py